### ISSUE TITLE
Breaking the typia performance advantage

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fast-json-stringify#631]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Currently typia has a higher performance than fast-json-stringify

We have to break it.
```[tasklist]
### Tasks
- [ ] https://github.com/fastify/fast-json-stringify/pull/632
```

**Comment by Uzlopak** [comment]
I have the next optimization in the pipeline. I assume we will be then atleast par with typia.

**Comment by mcollina** [comment]
Amazing work @Uzlopak!

**Comment by Uzlopak** [comment]
@mcollina 
Can we have a release please? I will ask the typia guy to do another benchmark. 

I think despite adding some optimizer like #633 we can not get better perf, without removing all the type checking.

**Comment by mcollina** [comment]
Done

**Comment by Tony133** [comment]
The optimization work tracked here was merged and released, so this issue has served its purpose.

Performance comparisons are now covered by the benchmarks in the repo and by the ongoing discussion in #782.

Closing as completed.
